<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ApproveSalaryRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'base' => [
                'numeric',
                'integer',
                'gt:0',
            ]
            ,
            'total' => [
                'numeric',
                'integer',
                'gt:0',
            ]
            ,
            'minus' => [
                'numeric',
                'gt:0',
            ]

//            'base' => 'numeric|integer|gt:0',
//            'total' => 'numeric|integer|gt:0',
//            'minus' => 'numeric|integer|gt:0',
        ];
    }

    public function messages()
    {
        return [
            '*.numeric' => 'Đừng nghịch nữa bạn à',
            '*.integer' => 'Đừng nghịch nữa bạn à',
            '*.gt' => 'Lương phải lớn hơn 0',
        ]; // TODO: Change the autogenerated stub
    }
}
