<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreDriverRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'name'=>'bail|required|filled|string',
            'gender'=>'bail|required|boolean',
            'id_numbers'=>'bail|required|string|size:12',
            'email'=>'bail|required|email',
            'phone_numbers'=>'bail|required|size:10',
            'birthdate'=>'bail|required|before:'.now()->subYears(18)->toDateString(),
            'file'=>'bail|required|image',
            'is_full'=>'required|boolean',
        ];
    }
    public function messages()
    {
        return [
            'name.required'=>'Vui lòng điền tên',
            'gender.required'=>'Vui lòng chọn giới tính',
            'gender.boolean'=>'Bạn ơi đừng nghịch nữa',
            'id_numbers.size'=>'Vui lòng nhập đúng CCCD/CMND',
            'email.email'=>'Email chưa đúng',
            'phone_numbers.size'=>'Số điện thoại nhập theo đầu số 0',
            'birthdate.before'=>'Tuổi chưa đủ',
            'file.image'=>'Hình như tải nhầm file',
            'is_full.boolean'=>'Bạn ơi đừng nghịch nữa',
        ]; // TODO: Change the autogenerated stub
    }
}
